-- C.W.B Payroll table
-- Run this once in Supabase > SQL Editor

create table if not exists public.payroll (
  id bigint generated by default as identity primary key,
  worker_name text not null,
  position text,
  salary_month text not null,
  base_salary numeric(14,2) not null default 0,
  allowance numeric(14,2) not null default 0,
  deductions numeric(14,2) not null default 0,
  net_salary numeric(14,2) not null default 0,
  payment_status text not null default 'Unpaid',
  payment_date date,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.payroll enable row level security;

drop policy if exists "CWB payroll select" on public.payroll;
drop policy if exists "CWB payroll insert" on public.payroll;

create policy "CWB payroll select"
on public.payroll
for select
to anon, authenticated
using (true);

create policy "CWB payroll insert"
on public.payroll
for insert
to anon, authenticated
with check (true);
